version: 3.8

services:
  app:
    user: "${UID}"
    hostname: "${HOST}"
    build:
      context: .
      docker: ./docker/Dockerfile
      args:
        USER_NAME: ${USER_NAME}
        USER_ID: ${UID}
    image: project-environment
    container_name: project-environment
    # env_file:
    #   ~.envs/.app

  volumes:
    - ./:/app
    - ~/.config/gcloud:${HOME}/.config/gcloud
  ports:
    - 8080:8080

  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

  ipc: host
  init: true